version: '2'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: "${HOSTNAME}"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://cellar.aniketrao.me'
        gitlab_rails['gitlab_shell_ssh_port'] = "${EXTERNAL_URL}"
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "${SMTP_ADDRESS}"
        gitlab_rails['smtp_port'] = "${SMTP_PORT}"
        gitlab_rails['smtp_authentication'] = "${SMTP_AUTHENTICATION}"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_user_name'] = "${SMTP_USERNAME}"
        gitlab_rails['smtp_password'] = "${SMTP_PASSWORD}"
        gitlab_rails['smtp_domain'] = "${SMTP_DOMAIN}"
    ports:
      - "${HTTP_CONTAINER_PORT}:${HTTP_PORT}"
      - "${SSL_CONTAINER_PORT}:${SSL_PORT}"
      - "${SSH_CONTAINER_PORT}:${SSH_PORT}"
    volumes:
      - '/srv/gitlab/config:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'